apiVersion: compliancetest/v1
kind: Implementation
metadata:
  name: tinyscheme
variants:
- metadata:
    displayName: Latest
    name: latest
  runtime:
    local: {}
  specifications:
  - r4rs
  testCommand:
  - tinyscheme
  - -c
  - (display $(PROGRAM))
