apiVersion: compliancetest/v1
exclusionTestSelector: 'r4rs: exclude'
kind: Specification
metadata:
  description: Revised(4) Report on the Algorithmic Language Scheme, Published 2 November
    1991
  displayName: R4RS
  labels:
    report: r4rs
  name: r4rs
sections:
- metadata:
    displayName: R4RS Core
    name: r4rs-core
  sections:
  - metadata:
      displayName: 6.1 Booleans
      name: booleans
    sections:
    - metadata:
        displayName: Literals
        name: literal
      testSelector: r4rs/heading=6.1, r4rs/literal=boolean, r4rs/essential=true
    - metadata:
        description: Not returns `#t` if obj is false, and returns `#f` otherwise.
        displayName: 'Essential Procedure: **not** _obj_'
        name: procedure-not
      testSelector: r4rs/heading=6.1, r4rs/literal=boolean, r4rs/essential=true
    testSelector: ""
  testSelector: ""
- metadata:
    displayName: R4RS Macros
    name: r4rs-macros
  optional: true
  testSelector: r4rs=macro
